#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>

#ifndef __TOS_BASE_OBJECT_TYPES_H__
#define __TOS_BASE_OBJECT_TYPES_H__

typedef enum
{
    TOS_RESULT_SUCCESS = 0,
    TOS_RESULT_ALREADY = 1,
    TOS_RESULT_FAILURE = -1,

    TOS_RESULT_ERROR = -1,
    TOS_RESULT_NOT_IMPLEMENTED = -2,
    TOS_RESULT_INVALID = -3,
    TOS_RESULT_NOT_FOUND = -4,
    TOS_RESULT_NOT_SUPPORTED = -5,
    TOS_RESULT_NOT_AVAILABLE = -6,
    TOS_RESULT_NOT_READY = -7,
    TOS_RESULT_NOT_PERMITTED = -8,
    TOS_RESULT_NOT_AUTHORIZED = -9,
    TOS_RESULT_NOT_AUTHENTICATED = -10,
    TOS_RESULT_NOT_ENOUGH_MEMORY = -11,
    TOS_RESULT_NOT_ENOUGH_RESOURCE = -12,
    TOS_RESULT_NOT_ENOUGH_SPACE = -13,
    TOS_RESULT_NOT_ENOUGH_DATA = -14,
    TOS_RESULT_NOT_ENOUGH_BUFFER = -15,
    TOS_RESULT_NOT_ENOUGH_STORAGE = -16,
    TOS_RESULT_NOT_ENOUGH_POWER = -17,
    TOS_RESULT_NOT_ENOUGH_BATTERY = -18,
    TOS_RESULT_NOT_ENOUGH_SIGNAL = -19,
    TOS_RESULT_NOT_ENOUGH_BANDWIDTH = -20,
    TOS_RESULT_NOT_ENOUGH_CPU = -21,
    TOS_RESULT_NOT_ENOUGH_IO = -22,
    TOS_RESULT_NOT_ENOUGH_NETWORK = -23,
    TOS_RESULT_NOT_ENOUGH_LINK = -24,
    TOS_RESULT_NOT_ENOUGH_SERVICE = -25,
    TOS_RESULT_NOT_ENOUGH_CONNECTION = -26,
    TOS_RESULT_NOT_ENOUGH_CHANNEL = -27,
    TOS_RESULT_NOT_ENOUGH_DEVICE = -28,
    TOS_RESULT_NOT_ENOUGH_DRIVER = -29,
    TOS_RESULT_NOT_ENOUGH_INTERFACE = -30,
    TOS_RESULT_NOT_ENOUGH_PROTOCOL = -31,
    TOS_RESULT_NOT_ENOUGH_PORT = -32,
    TOS_RESULT_NOT_ENOUGH_SOCKET = -33,

} TOS_Result_T;

typedef uint64_t TOS_BaseObjectID_T;

#endif