#include "../ThinkOS/TOS_Base4ALL.h"

#ifndef __PLATIF_IOC_EVTID_H__
#define __PLATIF_IOC_EVTID_H__
#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  IOC_EVT_CLASS_TEST = 1 << 0ULL,
  // TODO(@W): add more event class here
} IOC_EvtClass_T;

typedef enum {
  IOC_EVT_NAME_TEST_KEEPALIVE = 1 << 0ULL,

  IOC_EVT_NAME_TEST_MOVE_VERTICAL = 1 << 1ULL,
  IOC_EVT_NAME_TEST_MOVE_VERTICAL_ACK = 1 << 2ULL,

  IOC_EVT_NAME_TEST_MOVE_HORIZONTAL = 1 << 3ULL,
  IOC_EVT_NAME_TEST_MOVE_HORIZONTAL_ACK = 1 << 4ULL,

  IOC_EVT_NAME_TEST_COLLISION_DETECTED = 1 << 5ULL,
  IOC_EVT_NAME_TEST_COLLISION_DETECTED_ACK = 1 << 6ULL,

  IOC_EVT_NAME_TEST_BLOCK_SLEEP_5MS = 1 << 7ULL,
  IOC_EVT_NAME_TEST_NONBLOCK_SLEEP_1MS = 1 << 8ULL,

  // TODO(@W): add more event name here
} IOC_EvtNameTest_T;

#define IOC_defineEvtID(EvtClass, EvtName) ((IOC_EvtID_T)((EvtClass) | ((EvtName) << 16)))

#define IOC_EVTID_TEST_KEEPALIVE IOC_defineEvtID(IOC_EVT_CLASS_TEST, IOC_EVT_NAME_TEST_KEEPALIVE)
#define IOC_EVTID_TEST_MOVE_VERTICAL IOC_defineEvtID(IOC_EVT_CLASS_TEST, IOC_EVT_NAME_TEST_MOVE_VERTICAL)
#define IOC_EVTID_TEST_MOVE_VERTICAL_ACK IOC_defineEvtID(IOC_EVT_CLASS_TEST, IOC_EVT_NAME_TEST_MOVE_VERTICAL_ACK)
#define IOC_EVTID_TEST_MOVE_HORIZONTAL IOC_defineEvtID(IOC_EVT_CLASS_TEST, IOC_EVT_NAME_TEST_MOVE_HORIZONTAL)
#define IOC_EVTID_TEST_MOVE_HORIZONTAL_ACK IOC_defineEvtID(IOC_EVT_CLASS_TEST, IOC_EVT_NAME_TEST_MOVE_HORIZONTAL_ACK)
#define IOC_EVTID_TEST_COLLISION_DETECTED IOC_defineEvtID(IOC_EVT_CLASS_TEST, IOC_EVT_NAME_TEST_COLLISION_DETECTED)
#define IOC_EVTID_TEST_COLLISION_DETECTED_ACK \
  IOC_defineEvtID(IOC_EVT_CLASS_TEST, IOC_EVT_NAME_TEST_COLLISION_DETECTED_ACK)
#define IOC_EVTID_TEST_BLOCK_SLEEP_5MS IOC_defineEvtID(IOC_EVT_CLASS_TEST, IOC_EVT_NAME_TEST_BLOCK_SLEEP_5MS)
#define IOC_EVTID_TEST_NONBLOCK_SLEEP_1MS IOC_defineEvtID(IOC_EVT_CLASS_TEST, IOC_EVT_NAME_TEST_NONBLOCK_SLEEP_1MS)
// TODO(@W):

#ifdef __cplusplus
}
#endif
#endif /* __PLATIF_IOC_EVTID_H__ */