#define TOS_MAKE_EVTID(EvtMetaClassID, EvtMetaClassmateID) \
    ((((uint32_t)(EvtMetaClassID)&0xFF)<<24) | ((uint32_t)(EvtMetaClassmateID)&0x00FFFFFF))


#define TOS_EVTID_VEHICLE_STATE_TRANSFER \
    TOS_MAKE_EVTID(TOS_EVENT_CLASS_VEHICLE, TOS_EVENT_VEHICLE_STATE_TRANSFER)

#define TOS_EVTID_VEHICLE_EMERGENCY_STOP \
    TOS_MAKE_EVTID(TOS_EVENT_CLASS_VEHICLE, TOS_EVENT_VEHICLE_EMERGENCY_STOP)
#define TOS_EVTID_VEHICLE_EMERGENCY_STOP_ACK \
    TOS_MAKE_EVTID(TOS_EVENT_CLASS_VEHICLE, TOS_EVENT_VEHICLE_EMERGENCY_STOP_ACK)

#define TOS_EVTID_VEHICLE_EMERGENCY_STOPPED \
    TOS_MAKE_EVTID(TOS_EVENT_CLASS_VEHICLE, TOS_EVENT_VEHICLE_EMERGENCY_STOPPED)

#define TOS_EVTID_VEHICLE_EMERGENCY_RESOLVED \
    TOS_MAKE_EVTID(TOS_EVENT_CLASS_VEHICLE, TOS_EVENT_VEHICLE_EMERGENCY_RESOLVED)
#define TOS_EVTID_VEHICLE_EMERGENCY_RESOLVED_ACK \
    TOS_MAKE_EVTID(TOS_EVENT_CLASS_VEHICLE, TOS_EVENT_VEHICLE_EMERGENCY_RESOLVED_ACK)
//////////////////////

#define TOS_EVTID_SYSTEM_TIMER \
    TOS_MAKE_EVTID(TOS_EVENT_CLASS_SYSTEM, TOS_EVENT_SYSTEM_TIMER)